# Generated by Django 5.1.4 on 2024-12-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proprietor', models.CharField(max_length=100)),
                ('proprietor_address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('rent_start_date', models.DateField()),
                ('guarantee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('contract', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('status', models.CharField(choices=[('current', 'Current'), ('old', 'Old')], default='current', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('num_units', models.PositiveIntegerField(default=0)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='immo.gestion')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='immo.bien')),
            ],
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='immo.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='immo.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('current', 'Current'), ('old', 'Old')], default='current', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_tenants', to='immo.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_tenants', to='immo.unit')),
            ],
        ),
        migrations.CreateModel(
            name='GestionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('assistant', 'Assistant'), ('viewer', 'Viewer')], max_length=10)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immo.gestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immo.user')),
            ],
            options={
                'unique_together': {('user', 'gestion')},
            },
        ),
    ]
